### ISSUE TITLE
ws.url = q.url; 发生错误

### ISSUE THREAD

**Issue by 456vv** [liriliri/chii#10]
node -v
v14.15.1

打开页面：http://localhost:8080/tests/demo.html
chii发生错误退出了

 `D:\Program Files\node\node_modules\chii\server\lib\WebSocketServer.js:39
            ws.url = q.url;
                   ^

TypeError: Cannot set property url of #<WebSocket> which has only a getter
    at D:\Program Files\node\node_modules\chii\server\lib\WebSocketServer.js:39:20
    at WebSocketServer.completeUpgrade (D:\Program Files\node\node_modules\chii\node_modules\_ws@7.4.0@ws\lib\websocket-server.js:330:5)
    at WebSocketServer.handleUpgrade (D:\Program Files\node\node_modules\chii\node_modules\_ws@7.4.0@ws\lib\websocket-server.js:246:10)
    at Server.<anonymous> (D:\Program Files\node\node_modules\chii\server\lib\WebSocketServer.js:34:13)
    at Server.emit (events.js:315:20)
    at onParserExecuteCommon (_http_server.js:695:14)
    at onParserExecute (_http_server.js:608:3)
`

**Comment by Mr-Chilly** [comment]
Any news on this?

**Comment by xue-chao** [comment]
还没有解决

**Comment by changeLong** [comment]
+1

**Comment by tcstory** [comment]
meet the same problem

**Comment by LovelyYing** [comment]
edit WebSocketServer.js & comment line 'ws.url = q.url;'
then run again

**Comment by zhangyu921** [comment]
+1

**Comment by surunzi** [comment]
0.6.7 修复。
