### ISSUE TITLE
Issues while trying to run `chii` locally

### ISSUE THREAD

**Issue by JohnPaulHarold** [liriliri/chii#62]
Hello.

I'm trying to run `chii` as a local server and am seeing issues.

OS: OSX.

- I've cloned both `chii` and `depot_tools`.
- added `depot_tools` to my `PATH` and validated with `which gn` or `which gclient`
- Inside of `chii` I `cd` to `devtools` and run `gclient sync`
- I then `cd` back to the `chii` cloned repo root and run `npm i` and then `npm run build`

at this point, I see errors in the terminal. It's mostly the same looking error, here's the first:

```
[1/3404] ACTION //front_end:integration_test_runner-gen(//build/toolchain/linux:x64)
FAILED: gen/front_end/integration_test_runner.html 
python3 ../../third_party/node/node.py ../../scripts/build/ninja/copy-files.js /Users/jp/Code/chii/devtools/devtools-frontend/front_end /Users/jp/Code/chii/devtools/devtools-frontend/out/Default/gen/front_end integration_test_runner.html
Traceback (most recent call last):
  File "/Users/jp/Code/chii/devtools/devtools-frontend/out/Default/../../third_party/node/node.py", line 47, in <module>
    RunNode(args, output)
  File "/Users/jp/Code/chii/devtools/devtools-frontend/out/Default/../../third_party/node/node.py", line 24, in RunNode
    process = subprocess.Popen(cmd,
              ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 1950, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/jp/Code/chii/devtools/devtools-frontend/out/Default/../../third_party/node/mac/node-darwin-x64/bin/node'
```
My motivation for wanting to use `chii` is to help with Connected TV development, as not all devices offer chrome dev tools. I'd previously used `weinre` for this, but would like to move to something maintained.

Could you help advise what I'm doing wrong in the above?

**Comment by k-ezis** [comment]
Were you able to run npm install and init the depot tools with no issues? 

The only other issue I see is I run the npm run build and npm run dev:front_end from the outer chii folder not /dev_tools

**Comment by surunzi** [comment]
Use the npm package instead of building devtools yourself.
